export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium bank',
    heading: 'Unlimited and speedy transactions',
    subtitle: 'Get access to the future of wealth management.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/wallet.svg').default,
    alt:'wallet',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'services',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Modern planning for modern money',
    heading: 'Invest in Crypto and other digital assets',
    subtitle: 'We are well versed in dealing with all asset classes, both old and new.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/digital_currency.svg').default,
    alt:'wallet',
    dark: true,
    primary: false,
    darkText: true,

}

export const homeObjThree = {
    id: 'testimonials',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Proven results',
    heading: 'Unparalleled and competitive',
    subtitle: 'Check out our testimonials',
    buttonLabel: 'See the results of our past clients',
    imgStart: true,
    img: require('../../images/investment.svg').default,
    alt:'wallet',
    dark: true,
    primary: false,
    darkText: true,
}